# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-tag:
          - "5.4-cli"
        some-version:
          - "1.0"
          - "2.0"

    env:
      PHP_TAG: ${{ matrix.php-tag }}
      SOME_VERSION: ${{ matrix.some-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Which envs do we have?
        run: env | sort

      - name: Start composa
        run: docker-compose up -d

      - name: Read logs
        run: docker-compose logs -f php-cli
      - name: Long test
        run: for I in {1..10}; do echo -n .....; sleep 1; done
